version: 3
services:
  web:
    build: .
    ports:
      - "3000:3000"

  db:
    image: "postgres:11.1-alpine"
    environment:
      POSTGRES_USER: ewallet
      POSTGRES_DB: ewallet
      POSTGRES_PASSWORD: ewallet