source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sequel'
gem 'pg'
gem 'jwt'
gem 'dotenv'
gem 'rack-contrib'
gem 'pry'
gem 'bcrypt'
gem 'minitest'
gem 'rack-test'
gem 'database_cleaner'